[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm install --include=dev"]

[phases.build]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && npm start"
